name: build-gh-pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout litex-rowhammer-tester
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pythondata-misc-tapcfg sphinx sphinxcontrib-wavedrom

      - name: Build Sphinx documentation
        run: |
          make python-deps doc
          touch build/documentation/html/.nojekyll

      - name: Deploy gh-pages
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@3.6.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/documentation/html
          CLEAN: true
