name: test

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout litex-rowhammer-tester
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1

      - name: Install dependencies
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          sudo apt-get update -y
          sudo apt-get install -y git build-essential autoconf cmake ninja-build flex libfl-dev bison libftdi-dev
          sudo apt-get install -y libjson-c-dev libevent-dev libtinfo-dev uml-utilities python3 python3-venv python3-wheel
          make deps

      - name: Install conda
        run: |
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O conda_installer.sh
          bash conda_installer.sh -u -b -p ./conda_env
          source ./conda_env/etc/profile.d/conda.sh
          conda env create -f ./.github/scripts/environment.yml
          source ./conda_env/bin/activate xc7
          pip install -r requirements.txt

      - name: Check targets
        run: |
          source ./conda_env/bin/activate xc7
          make TARGET=arty
          make TARGET=zcu104
          make TARGET=lpddr4_test_board
          make TARGET=arty ARGS="--sim"

      - name: Run tests
        run: |
          source ./conda_env/bin/activate xc7
          make test


      - name: Build target
        run: |
          source ./conda_env/bin/activate xc7
          make TARGET=arty ARGS="--toolchain symbiflow" build
